database_in=file:/var/lib/aide/paszi-lab1.db
database_out=file:/var/lib/aide/paszi-lab1.db.new
gzip_dbout=no
report_url=stdout

PasziChecks = p+i+n+u+g+s+m+c+acl+xattrs+sha256

/etc/pam.d PasziChecks
/etc/security/pwquality.conf.d/99-paszi-lab1.conf PasziChecks
/etc/audit/rules.d/99-paszi-lab1.rules PasziChecks
/etc/ssh/sshd_config PasziChecks
/etc/ssh/sshd_config.d/99-paszi-lab1.conf PasziChecks
/etc/systemd/journald.conf.d/99-paszi-lab1.conf PasziChecks
/etc/nftables.conf PasziChecks
/srv/paszi-lab1/protected PasziChecks

