-- Отношения итоговой схемы ЛР1.
-- Внешние ключи добавляются в 02_relations.sql.
BEGIN;

CREATE TABLE customer (
    customer_id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   text NOT NULL
        CHECK (length(btrim(full_name)) > 0),
    phone       text NOT NULL,
    email       text
);

CREATE TABLE instrument_type (
    type_id     integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    description text NOT NULL
);

CREATE TABLE instrument (
    instrument_id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   integer NOT NULL,
    type_id       integer NOT NULL,
    inventory_no  text NOT NULL UNIQUE,
    name          text NOT NULL,
    maker         text,
    serial_no     text
);

CREATE TABLE employee (
    employee_id    integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      text NOT NULL,
    specialization text NOT NULL,
    work_email     text NOT NULL UNIQUE
);

CREATE TABLE restoration_order (
    order_id      integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id integer NOT NULL,
    accepted_on   date NOT NULL,
    due_on        date NOT NULL,
    status        text NOT NULL
        CHECK (status IN ('accepted', 'in_progress', 'ready',
                          'closed', 'cancelled')),
    complaint     text NOT NULL,
    CHECK (due_on >= accepted_on)
);

CREATE TABLE service (
    service_id         integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               text NOT NULL UNIQUE,
    description        text NOT NULL,
    base_price_kopecks integer NOT NULL
        CHECK (base_price_kopecks >= 0)
);

CREATE TABLE order_work (
    order_id             integer NOT NULL,
    line_no              integer NOT NULL CHECK (line_no > 0),
    service_id           integer NOT NULL,
    employee_id          integer NOT NULL,
    agreed_price_kopecks integer NOT NULL
        CHECK (agreed_price_kopecks >= 0),
    status               text NOT NULL
        CHECK (status IN ('planned', 'in_progress',
                          'done', 'cancelled')),
    PRIMARY KEY (order_id, line_no)
);

CREATE TABLE inspection (
    inspection_id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      integer NOT NULL,
    employee_id   integer NOT NULL,
    inspected_on  date NOT NULL,
    conclusion    text NOT NULL
        CHECK (length(btrim(conclusion)) > 0)
);

CREATE TABLE payment (
    payment_id     integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       integer NOT NULL,
    paid_on        date NOT NULL,
    amount_kopecks integer NOT NULL
        CHECK (amount_kopecks > 0),
    method         text NOT NULL
        CHECK (method IN ('cash', 'card', 'transfer')),
    receipt_no     text NOT NULL UNIQUE
);

COMMIT;
